library(LoLinR)
library(plyr)
library(extrafont)
library(fontcm)
loadfonts(quiet=TRUE)

rm(list=ls())
source('paths.R')
source('R/functions-analyses.R')
source('R/functions-figures.R')
load('output/RDatafiles/analyses_resultsAirSat@v50.RData')

toPdf(fig1(), 'output/figures/fig1.pdf', width=11.5, height=5.7)
toPdf(fig2(), 'output/figures/fig2.pdf', width=9.5, height=4.5)
toPdf(fig3(), 'output/figures/fig3.pdf', width=6, height=6)
toPdf(figS(), 'output/figures/figS.pdf', width=7.5, height=10)
