library(LoLinR)
library(plyr)
library(extrafont)
library(fontcm)
loadfonts(quiet=TRUE)

rm(list=ls())
source('paths.R')
source('R/functions-analyses.R')
source('R/functions-figures.R')
load('output/RDatafiles/analyses_resultsAirSat@v50.RData')

toPdf(comparisons(), 'output/figures/comparisons.pdf', width=9.5, height=4.5)
toPdf(comparisonsCIs(), 'output/figures/comparisonsCIs.pdf', width=9.5, height=4.5)
toPdf(comparisonsErect(), 'output/figures/comparisonsErect.pdf', width=6, height=6)
toPdf(comparisonsErectCIs(), 'output/figures/comparisonsErectCIs.pdf', width=6, height=6)
toPdf(michaelisMentenJAGS(), 'output/figures/michaelisMentenJAGS.pdf', width=7.5, height=10)
toPdf(massScaling(), 'output/figures/massScaling.pdf', width=7, height=7)
toPdf(fig1(), 'output/figures/fig1.pdf', width=11.5, height=5.7)