```{r, results='hide', warnings=FALSE, echo=FALSE, message=FALSE}
load('../output/RDatafiles/analyses_resultsAirSat@v50.RData')
source('../R/functions-analyses.R')
cleanbib()
myRefs   <-  listBibs()
exporBibs(myRefs, erase=FALSE)
```

**METHODS**  
*Organism collection and the estimation of tolerance to low oxygen conditions*  

We collected specimens of larger species (e.g. solitary ascidians) by peeling adults from the floating pontoons. Smaller species (e.g. bryozoans and colonial ascidians) were collected from pre-roughened acetate sheets that had been deployed at field sites according to standard methods (Hart and Marshall 2009), for two years prior to the experiment. The species used in these studies were classified according to their status (i.e. native or invasive to Australia) and their growth form (i.e. erect or flat; Table 1). All of the species came from the same study sites so as to prevent confounding site of origin effects. The organisms were transported to the lab in insulated aquaria with aerated seawater and acclimatized to laboratory conditions for 2 days in the dark at 19 ˚C. Unfortunately, the sites we used only had one native species with a flat growth form so we could not formally compare invasive and native species with that growth form.  
  
We measured oxygen consumption using two different closed respirometry systems, depending on the size of the study organism (Ferguson et al. 2013, Pettersen et al. 2015). Larger organisms were measured using hermetic 1.8 L chambers with circulating water connected to a 4-channel Firesting $\textrm{O}_\textrm{2}$ fiber optic oxygen meter (Pyro Sciences, Aachen-Germany). Smaller organisms were cut from acetate sheets and placed in 25 mL vials mounted on a 24-channel sensor dish reader (Sensor Dish Reader SDR, PreSens, Aachen- Germany). These systems were chosen because they do not consume oxygen, and have accurately estimated oxygen consumption and tolerance to low oxygen conditions for marine invertebrates in previous studies (Ferguson et al. 2013, Pettersen et al. 2015). The chambers and vials were filled with micro-filtered (0.2 μm), sterilized seawater that had been kept at 19 ˚C with constant aeration for at least 24 hours prior to experiments. Rates of oxygen consumption ($\dot{V}\textrm{O}_\textrm{2}$, mL h^-1^) were calculated as described in previous studies (White et al. 2011, Ferguson et al. 2013, Pettersen et al. 2015). Dry mass was determined after the oxygen consumption trials by drying each organism in an oven at 60 ˚C for one week, then weighing each individual with a precision balance (Adventurer Pro OHAUS, New Jersey, USA) to the nearest milligram.  
  
*Model*  
In contrast to what is observed for most vertebrates, where a clear $C_{C_{\textrm{O}_\textrm{2}}}$ can be discerned (Marshall et al. 2013), our $\dot{V}\textrm{O}_\textrm{2}$ data were curvilinear, such that there was no clear point where the organisms transitioned from oxyregulator to oxyconformer. Instead we fit a Michaelis-Menten function to our $\dot{V}\textrm{O}_\textrm{2}$ consumption data:  

$$\dot{V}\textrm{O}_\textrm{2} = \frac{\dot{V}\textrm{O}_\textrm{2}_{max} \times C\textrm{O}_\textrm{2}}{C_{50\%\dot{V}\textrm{O}_\textrm{2}} + C\textrm{O}_\textrm{2}}$$, (1)

where $\dot{V}\textrm{O}_\textrm{2}_{max}$ is an asymptotic $\dot{V}\textrm{O}_\textrm{2}$, and $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ is the value of $C\textrm{O}_\textrm{2}$ where $\dot{V}\textrm{O}_\textrm{2}_{max} / 2$. Importantly, in order to achieve model convergence, we employ a transformation to $\dot{V}\textrm{O}_\textrm{2}$. For each individual, we standardise $\dot{V}\textrm{O}_\textrm{2}$ based on its maximum value, so all individuals present a relative $\dot{V}\textrm{O}_\textrm{2}$ bounded between zero and one. We note that this transformation implicitly assumes that $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ is independent of body mass. In the appendix we demonstrate how this transformation does not affect our primary goal, which is to estimate $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ for each species.  
  
*Model Fitting and statistical tests*  
Sites were ranked according to the average of their water flow.  The effects of water flow on oxygen availability in the field were analyzed using linear models and mixed linear models. Ranking of each site according to flow was a fixed factor and sampling location and time (day) were random factors. **Marcelo, this paragraph is unclear, how exactly did you treat the data and tests?**  
  
For the $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ model, we fit equation (1) above in Bayesian framework by calling *JAGS* version 4.2.0 from the R package *R2jags* version 0.05-6 `r myCite('r2jags')` in order to derive posterior distributions and associated 95\% credible intervals (CIs) for the fitted parameters, $\dot{V}\textrm{O}_\textrm{2}_{max}$ and $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$. We allow $\dot{V}\textrm{O}_\textrm{2}_{max}$ and $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ to vary randomly among species. Random effects were assumed to be normally distributed, with means of 0. Fitted parameters were assigned priors that were vague (i.e. locally uniform over the region supported by the likelihood) `r myCite('kruschke2014book')`. The posterior distributions of model parameters were estimated using Markov chain Monte Carlo (MCMC) methods by constructing three chains of 1.5 $\times$ 10^6^ steps each, including 7.5 $\times$ 10^5^-step burn-in periods. Chains were thinned using a 375-step interval, so a total of 6,000 steps were retained to estimate posterior distributions (i.e. 3 $\times$ (1.5 $\times$ 10^6^ - 7.5 $\times$ 10^5^)/375 = 6,000).  

We use the species-specific estimates (*n* = `r length(unique(o2tab$species))`) for $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ obtained in *JAGS* in order to fit three separate ANOVA's: one to test for differences in $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ between species status (native and invasive), a second to test for differences in $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ between species shape (erect and flat), and a third one to test for differences in $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ between *erect* species status (native and invasive). Ideally, a fairer test would be represented by a two-way ANOVA with a formal statistical interaction between status and shape. However, given that we only have `r length(unique(o2tab$species))` species in our dataset, doing so would most likely overfit the data (i.e. too many parameters to be estimated from few observations), so our approach is conservative. We fit these ANOVA's for each one of the 6,000 MCMC parameter estimates in order to obtain a full 'posterior distribution' of differences in $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ between categories (status or shape). Statistical significance is judged by the lack of overlap between such distributions.  
  
**RESULTS**  
Our results indicate that native species present, on average, a $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ `r round(mean(results$native / results$invasive), 1)`-fold higher than that of invasive species. Similarly, erect species present, on average, a $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ `r round(mean(results$erect / results$flat), 1)`-fold higher than that of flat species (Figure comparisons.pdf). Within erect species only, native species present, on average, a $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ `r round(mean(resultsErect$native / resultsErect$invasive), 1)`-fold higher than that of invasive species (Figure comparisonsErect.pdf). Differences between status (native and invasive) among all species are still highly significant even when uncertainties around each ANOVA mean estimate are taken into account, but not as much for differences between shape (erect flat) among all species and differences between status (native and invasive) among erect species only (Figures comparisonsCIs.pdf and comparisonsErectCIs.pdf).  
  
**FIGURE LEGENDS**  

**comparisons.pdf**. Differences in $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ between species status (native and invasive, left panel), and between species shape (erect and flat, right panel). Each of the 6,000 circles for each category represents an average $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ estimated by ANOVA's using species-specific $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ estimated using a Michaelis-Menten function in *JAGS*.  
  
**comparisonsErect.pdf**.  Differences in $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ between status (native and invasive, left panel) for erect species only. Each of the 6,000 circles for each category represents an average $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ estimated by ANOVA's using species-specific $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ estimated using a Michaelis-Menten function in *JAGS*.  
  
**comparisonsCIs.pdf**.  Differences in $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ between species status (native and invasive, left panel), and between species shape (erect and flat, right panel). Each of the 6,000 circles and vertical lines for each category represent respectively an average $\pm$ S.E. $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ estimated by ANOVA's using species-specific $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ estimated using a Michaelis-Menten function in *JAGS*.  
  
**comparisonsErectCIs.pdf**.  Differences in $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ between status (native and invasive, left panel) for erect species only. Each of the 6,000 circles and vertical lines for each category represent respectively an average $\pm$ S.E. $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ estimated by ANOVA's using species-specific $C_{50\%\dot{V}\textrm{O}_\textrm{2}}$ estimated using a Michaelis-Menten function in *JAGS*.  
  
